[package]
name = "rusty-connect4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde= "1"
yew = "0.19.3"
yew-router = "0.16.0"
wasm-bindgen = "^0.2"
wee_alloc = "0.4.5"
wasm-logger = "0.2.0"

[lib]
crate-type = ["rlib", "cdylib"]